Repository Aniketsonii/hactoberit, pull requests merged in 2023-10, with the labels that each got.

#1 Create fetchmultiplewithdelay.js
  fetchmultiplewithdelay.js
Labels: enhancement

#3 Create rolehirachycode.py
  rolehirachycode.py
Labels: enhancement

#4 Add support for environment variables, minor bug fixes, & major refactor
  .gitignore
  01-polling/.example.env
  01-polling/app.js
  01-polling/fetchmultiplewithdelay.js
  01-polling/package-lock.json
  01-polling/package.json
  02-parse-json/parseJSon.js
Labels: bug, enhancement, hactober, hactober-fest

#11 Create unitconverter.py
  unitconverter.py
Labels: hactober, hactober-fest

#10 Create tictactoe.py
  tictactoe.py
Labels: hactober, hactober-fest

#9 Create blackjack.py
  blackjack.py
Labels: hactober, hactober-fest

#8 Create LRAH.py
  LRAH.py
Labels: hactober, hactober-fest

#6 Added comments to the code rolehirachycode.py
  rolehirachycode.py
Labels: hactober, hactober-fest
